import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 pt-32 pb-20 bg-background">
        <section className="px-6">
          <div className="max-w-3xl mx-auto prose-sm">
            <h1 className="text-4xl font-bold text-foreground mb-8">Terms of Service</h1>
            <p className="text-sm text-muted mb-4">Last updated: April 7, 2026</p>

            <div className="space-y-8 text-sm text-muted leading-relaxed">
              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">1. Service Description</h2>
                <p>
                  bConsulted First provides a free AI-powered preliminary Shopify operations audit
                  based on publicly visible storefront information. This audit is an automated
                  analysis tool and does not constitute professional consulting advice.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">2. Audit Scope and Limitations</h2>
                <p className="mb-3">
                  The preliminary audit is based entirely on publicly accessible storefront data.
                  It does not access your Shopify admin, internal systems, financial data, or
                  private business information.
                </p>
                <p>
                  The audit provides observations, scores, and recommendations based on
                  operational best-practice patterns. Results are generated by AI and should be
                  treated as preliminary indicators, not definitive assessments. We recommend a
                  human-led consultation for comprehensive operational analysis.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">3. No Guarantee of Results</h2>
                <p>
                  While we strive to provide useful and accurate analysis, we make no guarantees
                  regarding the completeness, accuracy, or applicability of audit findings to your
                  specific business situation. Operational improvements depend on many factors
                  beyond the scope of a preliminary review.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">4. User Responsibilities</h2>
                <p className="mb-3">By using our service, you agree to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide accurate contact information</li>
                  <li>Submit only store URLs that you are authorized to have reviewed</li>
                  <li>Not use the service for competitive intelligence or unauthorized purposes</li>
                  <li>Not attempt to overwhelm or abuse the service through automated submissions</li>
                </ul>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">5. Intellectual Property</h2>
                <p>
                  All content, design, and functionality of the bConsulted First website and audit
                  reports are owned by bConsulted First. Audit reports are provided for your
                  internal use and may not be redistributed or published without permission.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">6. Consulting Services</h2>
                <p>
                  Paid consulting services are subject to separate engagement agreements.
                  The free audit does not create a consulting relationship or obligation on
                  either party.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">7. Limitation of Liability</h2>
                <p>
                  bConsulted First shall not be liable for any indirect, incidental, special, or
                  consequential damages arising from the use of our audit service or website.
                </p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-foreground mb-3">8. Contact</h2>
                <p>
                  For questions about these terms, contact us at{" "}
                  <a href="mailto:legal@bconsultedfirst.com" className="text-primary hover:text-accent">
                    legal@bconsultedfirst.com
                  </a>.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
